web:
  build: .
  command: foreman start
  ports:
   - "80:5000"
   - "443:5000"
  volumes:
   - .:/app
  links:
   - redis
  environment:
    RACK_ENV: production
    RAILS_SECRET_KEY_BASE: cce6f9a6e8da3b6e2b83740758b4496b3bea0330825cfa0dd15d3a4d6f875e05
redis:
  image: redis
  ports:
    - "6379"
